# Docker Compose configuration for Permoney
# 
# This file allows you to run Permoney on your local machine or on a cloud VPS.
# 
# Quick start:
# 1. Download this file: curl -o compose.yml https://raw.githubusercontent.com/hendripermana/permoney/main/compose.example.yml
# 2. Create .env file: cp .env.example .env
# 3. Start the app: docker-compose up -d
# 
# For detailed instructions, see:
# https://github.com/hendripermana/permoney/blob/main/docs/hosting/docker.md
# 
# For support and questions:
# https://github.com/hendripermana/permoney/discussions/categories/general

version: "3.8"

services:
  # Main web application
  web:
    # NOTE: enabling OpenAI will incur costs when you use AI-related features in the app (chat, rules).  Make sure you have set appropriate spend limits on your account before adding this.
    image: ghcr.io/hendripermana/permoney:latest
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    environment:
      - OPENAI_ACCESS_TOKEN=${OPENAI_ACCESS_TOKEN:-}
      - TWELVE_DATA_API_KEY=${TWELVE_DATA_API_KEY:-}
      - ALPHA_VANTAGE_API_KEY=${ALPHA_VANTAGE_API_KEY:-}
      - BRAND_FETCH_CLIENT_ID=${BRAND_FETCH_CLIENT_ID:-}
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/permoney_production
      - REDIS_URL=redis://redis:6379/1
      - RAILS_ENV=production
      - RAILS_SERVE_STATIC_FILES=true
      - RAILS_LOG_TO_STDOUT=true
    networks:
      - permoney_net

  # Background job processor
  worker:
    image: ghcr.io/hendripermana/permoney:latest
    command: bundle exec sidekiq
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/permoney_production
      - REDIS_URL=redis://redis:6379/1
      - RAILS_ENV=production
      - RAILS_LOG_TO_STDOUT=true
    networks:
      - permoney_net

  # PostgreSQL database
  db:
    image: postgres:17
    environment:
      - POSTGRES_DB=permoney_production
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - permoney_net

  # Redis for caching and background jobs
  redis:
    image: redis:latest
    networks:
      - permoney_net

volumes:
  postgres_data:

networks:
  permoney_net:
