concurrency: 8
queues:
  - [scheduled, 10] # For cron-like jobs (e.g. "daily market data sync")
  - [high_priority, 4]
  - [medium_priority, 2]
  - [low_priority, 1]
  - [default, 1]

:schedule:
  brankas_sync_job:
    cron: "0 */6 * * *"   # every six hours
    class: "Brankas::SyncJob"
